/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SkLoaderImage {
        "animated": boolean;
    }
    interface SkLoaderParagraph {
        "align": 'left' | 'center' | 'right';
        "animated": boolean;
        "indent": boolean;
        "rows": number;
    }
}
declare global {
    interface HTMLSkLoaderImageElement extends Components.SkLoaderImage, HTMLStencilElement {
    }
    var HTMLSkLoaderImageElement: {
        prototype: HTMLSkLoaderImageElement;
        new (): HTMLSkLoaderImageElement;
    };
    interface HTMLSkLoaderParagraphElement extends Components.SkLoaderParagraph, HTMLStencilElement {
    }
    var HTMLSkLoaderParagraphElement: {
        prototype: HTMLSkLoaderParagraphElement;
        new (): HTMLSkLoaderParagraphElement;
    };
    interface HTMLElementTagNameMap {
        "sk-loader-image": HTMLSkLoaderImageElement;
        "sk-loader-paragraph": HTMLSkLoaderParagraphElement;
    }
}
declare namespace LocalJSX {
    interface SkLoaderImage {
        "animated"?: boolean;
    }
    interface SkLoaderParagraph {
        "align"?: 'left' | 'center' | 'right';
        "animated"?: boolean;
        "indent"?: boolean;
        "rows"?: number;
    }
    interface IntrinsicElements {
        "sk-loader-image": SkLoaderImage;
        "sk-loader-paragraph": SkLoaderParagraph;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sk-loader-image": LocalJSX.SkLoaderImage & JSXBase.HTMLAttributes<HTMLSkLoaderImageElement>;
            "sk-loader-paragraph": LocalJSX.SkLoaderParagraph & JSXBase.HTMLAttributes<HTMLSkLoaderParagraphElement>;
        }
    }
}
