/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SkLoaderImage {
        "animated": boolean;
    }
    interface SkLoaderText {
        "align": 'left' | 'center' | 'right';
        "animated": boolean;
        "indent": boolean;
        "rows": number;
    }
}
declare global {
    interface HTMLSkLoaderImageElement extends Components.SkLoaderImage, HTMLStencilElement {
    }
    var HTMLSkLoaderImageElement: {
        prototype: HTMLSkLoaderImageElement;
        new (): HTMLSkLoaderImageElement;
    };
    interface HTMLSkLoaderTextElement extends Components.SkLoaderText, HTMLStencilElement {
    }
    var HTMLSkLoaderTextElement: {
        prototype: HTMLSkLoaderTextElement;
        new (): HTMLSkLoaderTextElement;
    };
    interface HTMLElementTagNameMap {
        "sk-loader-image": HTMLSkLoaderImageElement;
        "sk-loader-text": HTMLSkLoaderTextElement;
    }
}
declare namespace LocalJSX {
    interface SkLoaderImage {
        "animated"?: boolean;
    }
    interface SkLoaderText {
        "align"?: 'left' | 'center' | 'right';
        "animated"?: boolean;
        "indent"?: boolean;
        "rows"?: number;
    }
    interface IntrinsicElements {
        "sk-loader-image": SkLoaderImage;
        "sk-loader-text": SkLoaderText;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sk-loader-image": LocalJSX.SkLoaderImage & JSXBase.HTMLAttributes<HTMLSkLoaderImageElement>;
            "sk-loader-text": LocalJSX.SkLoaderText & JSXBase.HTMLAttributes<HTMLSkLoaderTextElement>;
        }
    }
}
